name: Create PR after push

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set Branch Name
        run: echo "BRANCH_NAME=review/auto-pr-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: PR autom치tico para an치lise"
          branch: ${{ env.BRANCH_NAME }}
          title: "游댌 PR Autom치tico - ${{ env.BRANCH_NAME }}"
          body: |
            Este PR foi criado automaticamente ap칩s push na main.
            Branch gerada: `${{ env.BRANCH_NAME }}`.
          delete-branch: true
