name: DEV - Create PR from develop to main

on:
  push:
    branches:
      - feature

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: develop
          title: 'Merge feature into develoṕ'
          body: 'Pull request automático para atualizar a branch develoṕ com as mudanças da feature.'