name: DEV - Create PR from develop to main

on:
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: develop
          title: 'Merge develop into main'
          body: 'Pull request automático para atualizar a branch main com as mudanças da develop.'
          draft: false