name: publish

on:
  push:
    branches: main

jobs:
  build:
    if: github.actor != 'readme-generate'
    uses: alves-dev/actions/.github/workflows/build-docker.yml@v1
    with:
      image-name: ghcr.io/alves-dev/readme-generate